# Make sure the directory names ends with "/"
---
CORE:
  APPLICATION_NAME: gpdbinstall                           # Application Folder Name
  OS: "linux"                                             # OS Platform
  ARCH: "amd64"                                           # OS Architecture
  GO_BUILD: "1.12.9"                                      # Version of GO the Application will use to Build (eg. 1.7.4)
  BASE_DIR: /home/gpadmin                                 # Location Where [APPLICATION_NAME] Files Will Be Created
  TEMP_DIR: /temp/                                        # Temporary Folder Inside [APPLICATION_NAME] for Hostfile and Init
DOWNLOAD:
  API_TOKEN: <GITHUB RELEASE>                             # You can get it after login to PivNet
  DOWNLOAD_DIR: /download/                                # Folder Inside [APPLICATION_NAME]: stores binares
INSTALL:
  ENV_DIR: /env/                                          # Folder Inside [APPLICATION_NAME]: stores source files
  UNINTSALL_DIR: /uninstall/                              # Folder Inside [APPLICATION_NAME]: stores uninstall info
  FUTUREREF_DIR: /future_reference/                       # Folder Inside [APPLICATION_NAME]: stores configuration info
  MASTER_USER: gpadmin                                    # User that will install GPDB s/w usually "gpadmin"
  MASTER_PASS: changeme                                   # Password of MASTER_USER user
  GPMON_PASS: changeme                                    # Password for GPMON
  MASTER_DATA_DIRECTORY: /home/gpadmin/data/master/       # Master Data Directory
  SEGMENT_DATA_DIRECTORY: /home/gpadmin/data/primary/     # Segment Data Directory
  MIRROR_DATA_DIRECTORY: /home/gpadmin/data/mirror/       # Mirror Data Directory
  TOTAL_SEGMENT: 2                                        # Total Segments to be created
